### ISSUE TITLE
antivirus deletes exe after using "fix icon"

### ISSUE THREAD

**Issue by RayFB-13** [TurboWarp/packager-extras#2]
if u use the fix icon option + installer, The exe gets deleted, then I get a message from my antivirus.
if u use the fix icon option but no installer, The exe gets deleted, but I don't get a message from my antivirus.

**Comment by GarboMuffin** [comment]
What antivirus software are you using?

**Comment by RayFB-13** [comment]
McAfee

**Comment by era2010-coder** [comment]
You can Uninstall your antivirus software

**Comment by RayFB-13** [comment]
we can try using [how this works](https://processhacker.sourceforge.io/).

**Comment by RayFB-13** [comment]
> You can Uninstall your antivirus software

or we can try using [how this works](https://processhacker.sourceforge.io/) [(github here!)](https://github.com/processhacker/processhacker).

**Comment by GarboMuffin** [comment]
It's common for antivirus software to mark all unknown software as viruses. The executable files generated by this program are almost certainly unique files that antivirus software has never seen before, so that's not unexpected.

Not much I can really do to avoid problems with these blackbox software packages. My only advice would be to switch to a different (better) antivirus if you feel that your current one has too many false positives.

If I wanted to infect your computer I could just put a virus in the website instead of in a separate optional program.

**Comment by RayFB-13** [comment]
why not use [this](https://github.com/processhacker/processhacker)?

**Comment by GarboMuffin** [comment]
What would process hacker be useful for?

**Comment by RayFB-13** [comment]
wrong software... I meant resource hacer, for changing stuff without code

**Comment by GarboMuffin** [comment]
TurboWarp Packager Extras uses a combination of Pillow (the most widely used Python image manipulation tool) and rcedit (from the very widely used Electron project) to change the application icon automatically. If that's triggering your antivirus then resource hacker almost certainly will as well.

**Comment by RayFB-13** [comment]
no, it will not detect it.
