### ISSUE TITLE
ICON DOENST GET FIXED

### ISSUE THREAD

**Issue by Nickzie** [TurboWarp/packager-extras#24]
Please Help I Need My Custom Icon To Work

Else People Might Think It's A Virus!

**Comment by GarboMuffin** [comment]
Sometimes the icon doesn't update immediately on your computer. If you could share the logs that appear or any error messages, that would be helpful

But really, using Extras is discouraged because, *using it makes antivirus software even more suspicious, not less*

If you don't want people to think you're sending a virus, use plain HTML instead

<details><summary>off topic:</summary>SCREAMING at unpaid volunteers does not make them eager to fix your issue</details>
